# Data
All data for this project has been provided through the Detroit Open Data Portal. Two data files are provided for use in training and validating our models: train.csv and test.csv. Each row in these two files corresponds to a single blight ticket, and includes information about when, why, and to whom each ticket was issued. The target variable is compliance, which is True if the ticket was paid early, on time, or within one month of the hearing data, False if the ticket was paid after the hearing date or not at all, and Null if the violator was found not responsible. Compliance, as well as a handful of other variables that will not be available at test-time, are only included in train.csv.

Note: All tickets where the violators were found not responsible are not considered during evaluation. They are included in the training set as an additional source of data for visualization, and to enable unsupervised and semi-supervised approaches. However, they are not included in the test set.

```{python python_libraries}
import pandas as pd
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn import preprocessing 
from sklearn.preprocessing import LabelEncoder
from sklearn import model_selection, metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
```

