---
title: "Random Forests with Python"
author: "John James jjames@datasciencesalon.org"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  rmdformats::readthedown:
    highlight: kate
    css: ../css/rmdStyles.css
    number_sections: false
editor_options: 
  chunk_output_type: inline
---


```{r knitr_init, echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE}
options(knitr.table.format = "html")
options(max.print=100, scipen=999, width = 800)
knitr::opts_chunk$set(echo=TRUE,
	             cache=FALSE,
               prompt=FALSE,
	             eval = TRUE,
               tidy=TRUE,
               root.dir = "..",
               fig.height = 8,
               fig.width = 20,
               comment=NA,
               message=FALSE,
               warning=FALSE)
knitr::opts_knit$set(width=100, figr.prefix = T, figr.link = T)
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
```

```{r r_libraries}
library(dplyr)
library(knitr)
library(kableExtra)
library(kfigr)
library(reticulate)
```

```{python path}
import os
sys.path.append("..")
````


```{python intro, child = 'intro.rmd'}
```

***

```{python rf, child = 'data.rmd'}
```

***

```{python rf, child = 'rf.rmd'}
```

***

```{python model, child = 'model.rmd'}
```

***

```{python prediction, child = 'prediction.rmd'}
```

***

```{python evaluation, child = 'eval.rmd'}
```

***

```{python conclusion, child = 'conclusion.rmd'}
```

***


```{python appendix, child = 'appendix.rmd'}
```

***